import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ArticleCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  content: string;
}

export class Article {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  content: string;
}
